### ISSUE TITLE
getting error on client-side code

### ISSUE THREAD

**Issue by anoop-chauhan** [elmamc/AngularCli#1]
Hi @elmamc , Thanks for creating this project but on running client-side code getting this error
```
ERROR in ./src/main.ts
Module not found: Error: Can't resolve 'meteor-client.js' in '/home/learning/meteor/AngularCli/client/src'
```

**Comment by elmamc** [comment]
Hi @anoop-chauhan 
Maybe you have to install and configure the meteor-client-bundler.
I followed the process explained in the[ IonicCli+Meteor Tutorial](https://angular-meteor.com/tutorials/whatsapp2/ionic/meteor-server-side) 
at the "Preparing the Meteor Client" Paragraph.
After installing meteor-client-bundler, you have to add the bundling script to the packages.json of the AngularCli client .
The script has to point to the server directory.
This is the only script i added
`"meteor-client:bundle": "meteor-client bundle -s ../server"`

Then, you have to run `npm run meteor-client:bundle` in your AngularCli client directory, this will generate the meteor-client.js file in the Client's node_modules dir that will import in the main of your client

**Comment by anoop-chauhan** [comment]
Thanks @elmamc , working fine now 👍🏼
